# Generated by Django 2.0 on 2019-09-20 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Our Achievements',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=500, verbose_name='Market Center Name')),
                ('product', models.CharField(max_length=500, verbose_name='Products/Services')),
                ('contact_person', models.CharField(max_length=500, verbose_name='Contact Person')),
                ('division', models.CharField(max_length=500, verbose_name='Division')),
                ('town', models.CharField(max_length=500, verbose_name='Town')),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Contact Person's Email")),
                ('contact_person_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact Person's Phone Number")),
                ('contact_facebook_account', models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact Person's Facebook Account")),
                ('contact_telegram_account', models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact Person's Telegram Account")),
            ],
            options={
                'verbose_name_plural': 'Business Agents',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', djrichtextfield.models.RichTextField(verbose_name='Content')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog photos')),
                ('slug', models.SlugField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Regional Contact Persons',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=200, verbose_name='Good/Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=500, verbose_name='Document Name')),
                ('document', models.FileField(upload_to='Documents')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=200, verbose_name='Business Name')),
                ('registration', models.CharField(max_length=100, verbose_name='Registration Name')),
                ('business_type', models.CharField(max_length=200, verbose_name='Business Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, verbose_name='ID Number')),
                ('cell', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('farm', models.CharField(max_length=200, verbose_name='Type of Farming')),
                ('size', models.CharField(max_length=200, verbose_name='Farm Size')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cell', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter Account Link')),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter Account Link')),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.County')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=500, verbose_name='Market Center Name')),
                ('product', models.CharField(max_length=500, verbose_name='Products/Services')),
                ('contact_person', models.CharField(max_length=500, verbose_name='Contact Person')),
                ('division', models.CharField(max_length=500, verbose_name='Division')),
                ('town', models.CharField(max_length=500, verbose_name='Town')),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Contact Person's Email")),
                ('contact_person_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name="Contact Person's Phone Number")),
                ('contact_facebook_account', models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact Person's Facebook Account")),
                ('contact_telegram_account', models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact Person's Telegram Account")),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County', verbose_name='County')),
            ],
            options={
                'verbose_name_plural': 'Business Market Centers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, verbose_name='ID Number')),
                ('cell', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter Account Link')),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter Account Link')),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('market_center', models.CharField(blank=True, max_length=300, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.County')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(help_text='max. 20 char', max_length=200)),
                ('image_description', models.CharField(help_text='Short Description(Max 80 Char)', max_length=800)),
                ('image', models.ImageField(upload_to='sliders')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, verbose_name='ID Number')),
                ('cell', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution of Learning')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('course', models.CharField(max_length=200, verbose_name='Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county', models.CharField(max_length=500)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County')),
            ],
            options={
                'verbose_name_plural': 'Sub Counties',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='county', chained_model_field='county', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubCounty'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubCounty', verbose_name='Sub County'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sub_county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='county', chained_model_field='county', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SubCounty'),
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.County', verbose_name='County'),
        ),
        migrations.AddField(
            model_name='agent',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubCounty', verbose_name='Sub County'),
        ),
    ]
